### ISSUE TITLE
db only accepts single values?

### ISSUE THREAD

**Issue by enthusi** [theandrew168/bronzebeard#10]
AssemblerError: invalid syntax in expr: "4 0xb1 0x05 0x3a 0x3a"
line 425: db                4, 0xb1, 0x05, 0x3a, 0x3a

"bytes  4, 0xb1, 0x05, 0x3a, 0x3a", however, works.

**Comment by theandrew168** [comment]
Unfortunately, multiple values with db/dh/dw isn't possible with how the assembler is currently designed. An important distinction between "bytes" and "pack" is that pack allows for expressions and/or references to existing labels. Bytes only allows literal values. 

To that end, since expressions can look very different, it isn't possible for a given keyword to support both expressions AND multiple values. They are mutually exclusive.

That being said, I did expand the "bytes" line of keywords with more options for other integer sizes (and even floats). It doesn't perfectly match the nasm db/dh/dw behavior but I had to find a workable balance.

You can read more about these new [numeric sequence literals](https://github.com/theandrew168/bronzebeard/tree/master/docs#numeric-sequence-literals).

Some examples:
```
bytes 1 2 0x03 0b100 5 0x06 0b111 8
bytes -1 0xff  # same value once encoded as 2's comp integers
shorts 0x1234 0x5678
ints  1 2 3 4
longs 1 2 3 4  # same as above (both 4 bytes each)
floats 3.141 2.3455
```
