### ISSUE TITLE
operand recognition in 0.1.7

### ISSUE THREAD

**Issue by enthusi** [theandrew168/bronzebeard#12]
sw	ra,(sp)
AssemblerError: invalid syntax in expr: "sp )"

lhu a2,(a0)
AssemblerError: invalid syntax in expr: "a0 )"

both work with a leading 0 such as in sw ra, 0(sp)

**Comment by theandrew168** [comment]
This is currently intentional. The alternate offset syntax requires a specific arrangement of tokens in order to be distinguished from the "regular" syntax by the parser. The specific arity of an instruction's arguments as well as the explicit index of the opening paren are required in order for the alt syntax to be detected (this also restricts the immediate to a single token in such situations).

Given the ability to "fix" this by being explicit about the 0 offset, I'm going to leave the syntax unchanged for the time being.
