### ISSUE TITLE
It just works!

### ISSUE THREAD

**Issue by aw** [theandrew168/bronzebeard#7]
Hi Andrew,

I updated my local git repo and rebuilt the latest version, then used it to compile a previously compiled program and the **md5 checksum** is identical to the last built version from February (and the build is still super fast).

So awesome, thank you for this tool.

**Comment by theandrew168** [comment]
Alex,

Good to hear and thanks for the praise! I've definitely been busy with making the assembler better / more usable over the past few weeks. In pursuit of a stable and useful v1.0.0, I've actually chosen to introduce one potentially-breaking change. The way the assembler handles string literals now does a better job of keeping the value as raw as possible (this required a custom clause in the lexer). In short, instead of just joining the string tokens following with a space, I now preserve the literal content up to the next newline. The regex used for this is essentially: `string (.*)`. With this change, the `string` keyword can now be used to embed quotes, multiple spaces, and even `#` characters which would normally be treated as comments.

There have also been a decent number of new features added since February: [shorthand pack keywords](https://github.com/theandrew168/bronzebeard/tree/master/docs#shorthand-syntax), [alternate offset syntax](https://github.com/theandrew168/bronzebeard/blob/ba8503d43478376e162a1719b30e73184253298f/tests/test_asm.py#L1408), and [pseudo-instructions](https://github.com/theandrew168/bronzebeard/tree/master/docs#shorthand-syntax) are the main standouts.

Moving forward, I still have a few things I want to wrap up before releasing v1. I need to implement the logic to automatically detect and compress instructions (if the `--compress` flag is provided) and I want to setup a more official documentation site on readthedocs. It shouldn't take too much more time and I'm excited for the big release!

Thanks again for the comments. It gives me motivation to know that folks are using this project and find it useful.
